on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  waf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure and Build
        run: python waf configure build
