on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  waf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run:
          name: Configure
          command: python waf configure
